### PR TITLE
Remove ex_admin images, add bg image, add some css fixes

### PR DESCRIPTION
**Pull request by ericworkman**
@mbramson I liked what @Serneum did with tabletop, so I did something similar. 

image

### CODE REVIEW

**Review by mbramson — APPROVED** [review]
LGTM

**Review by Serneum — APPROVED** [review]
LGTM

**Comment by Serneum** [comment]
@ericworkman I forgot to actually have you check what happens if the container is longer than the view window. In my case, I had to add `height: 100%` to `body` so that it would render properly

**Comment by ericworkman** [comment]
@Serneum Have a screenshot of that?

**Comment by Serneum** [comment]
I will try and reproduce it, but I can describe a bit of what I was seeing. The list of Games in CoverMyTableTop was longer than the what was currently visible in the browser, so once you scrolled down, the container would just stop and the list would keep going beyond the bounds of the container. Instead of having the white background, they'd be on top of the background image

I had solved it by adding a `min-height: 100%`, not a `height: 100%`

**Comment by ericworkman** [comment]
I see. Yeah, please try to reproduce it. So far I'm not able to.

**Pull request merged**
