### PR TITLE
Refactor GroupController and PairRetroController to use @authorized_conn

### PR DESCRIPTION
**Pull request by mbramson**
Let me know what you think of this refactor. If this style makes sense and makes it more readable, I'd like to apply it to other controllers. Thoughts?

### CODE REVIEW

**Comment by ericworkman** [comment]
I like this!

**Comment by mbramson** [comment]
@daveshah showed me that it is in fact possible to import @authorized_conn from a different module, so I'm going to get that working before this is merged.

**Comment by mbramson** [comment]
Managed to extract @authorized_conn to web/web.ex with little issue, and also apply this refactor to the PairRetroControler as well. This should be good to go.

**Review by ericworkman — APPROVED** [review]
LGTM I definitely like this way better than the previous

**Pull request merged**
